AuctionHouseHelper.Constants.DialogNames = {
  CreateShoppingList = "AUCTION_HOUSE_HELPER_CREATE_SHOPPING_LIST",
  DeleteShoppingList = "AUCTION_HOUSE_HELPER_DELETE_SHOPPING_LIST",
  AddItemToShoppingList = "AUCTION_HOUSE_HELPER_ADD_ITEM_TO_SHOPPING_LIST",
  RenameShoppingList = "AUCTION_HOUSE_HELPER_RENAME_SHOPPING_LIST",

  SellingConfirmPost = "AUCTION_HOUSE_HELPER_SELLING_CONFIRM_POST",
  SellingConfirmUnhideAll = "AUCTION_HOUSE_HELPER_SELLING_CONFIRM_UNHIDE_ALL",
}
