AuctionHouseHelper.Selling.Events.RefreshHistory = "selling_refresh_history"
AuctionHouseHelper.Selling.Events.SellSearchStart = "sell_search_start"
AuctionHouseHelper.Selling.Events.PriceSelected = "price_selected"
AuctionHouseHelper.Selling.Events.RefreshSearch = "selling_refresh_search"
AuctionHouseHelper.Selling.Events.ShowConfirmPurchase = "selling_confirm_commodity_callback"
